import { Course } from "@/types/course";

export const defaultStudentAvatars = [
    "/avatars/avatar-1.png",
    "/avatars/avatar-2.png",
    "/avatars/avatar-3.png",
    "/avatars/avatar-4.png",
];

export const showcaseStudentAvatars = [
    "/avatars/testimonial-1.png",
    "/avatars/testimonial-2.png",
    "/avatars/testimonial-3.png",
    "/avatars/testimonial-1.png",
];

export const coursesData: Course[] = [
    {
        id: "1",
        title: "Learn Figma from Basic",
        instructor: "purepearl studio",
        rating: 4.5,
        lessons: 17,
        duration: "2 hours 16 mins",
        comments: 59,
        level: "Beginner",
        price: 25,
        priceType: "/lifetime",
        image: "/courses/course-1.png",
        category: "UI/UX Design",
    },
    {
        id: "2",
        title: "Build Digital Asset",
        instructor: "purepearl studio",
        rating: 4.5,
        lessons: 17,
        duration: "2 hours 16 mins",
        comments: 59,
        level: "Beginner",
        price: 25,
        priceType: "/lifetime",
        image: "/courses/course-2.png",
        category: "Graphic Design",
    },
    {
        id: "3",
        title: "the Power of Big Data",
        instructor: "purepearl studio",
        rating: 4.5,
        lessons: 17,
        duration: "2 hours 16 mins",
        comments: 59,
        level: "Beginner",
        price: 25,
        priceType: "/lifetime",
        image: "/courses/course-3.png",
        category: "Data Science",
    },
    {
        id: "4",
        title: "Balancing Productivity and Life",
        instructor: "purepearl studio",
        rating: 4.5,
        lessons: 17,
        duration: "2 hours 16 mins",
        comments: 59,
        level: "Beginner",
        price: 25,
        priceType: "/lifetime",
        image: "/courses/course-4.png",
        category: "UI/UX Design",
    },
    {
        id: "5",
        title: "Mastering Money Management",
        instructor: "purepearl studio",
        rating: 4.5,
        lessons: 17,
        duration: "2 hours 16 mins",
        comments: 59,
        level: "Beginner",
        price: 25,
        priceType: "/lifetime",
        image: "/courses/course-5.png",
        category: "Finance",
    },
    {
        id: "6",
        title: "From Idea to Startup Success",
        instructor: "purepearl studio",
        rating: 4.5,
        lessons: 17,
        duration: "2 hours 16 mins",
        comments: 59,
        level: "Beginner",
        price: 25,
        priceType: "/lifetime",
        image: "/courses/course-6.png",
        category: "Marketing",
    },
];

export const categoryRows = [
    [
        "Featured",
        "Music",
        "Drawing & Painting",
        "Marketing",
        "Animation",
        "Social Media",
        "UI/UX Design",
        "Creative Marketing",
    ],
    [
        "Digital Illustration",
        "Film & Video",
        "Crafts",
        "Freelance & Entrepreneurship",
        "Graphic Design",
        "Photography",
    ],
    [
        "Productivity",
        "Web Development",
        "Data Science",
        "Cooking",
    ],
];
